# Generated by Django 4.2.9 on 2024-01-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('passphrase', models.TextField(db_column='password', max_length=250)),
            ],
            options={
                'db_table': 'userprofile',
                'managed': False,
            },
        ),
    ]
