# Generated by Django 4.2.9 on 2024-01-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_user_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
