# Generated by Django 4.2.9 on 2024-01-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_delete_token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
