# Generated by Django 4.2.9 on 2024-01-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_pofile',
        ),
    ]
